<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>documento</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Documento_files/libs/clipboard/clipboard.min.js"></script>
<script src="Documento_files/libs/quarto-html/quarto.js"></script>
<script src="Documento_files/libs/quarto-html/popper.min.js"></script>
<script src="Documento_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Documento_files/libs/quarto-html/anchor.min.js"></script>
<link href="Documento_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Documento_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Documento_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Documento_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Documento_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Documento_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="Documento_files/libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="Documento_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="Documento_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="Documento_files/libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="Documento_files/libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="Documento_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="Documento_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<style>

html {
  font-size: 12px;
}

body {
  font-size: 0.75rem;
}

h3 {
  text-align: left;
}

.center h2 {
  text-align: center;
}

.center h3 {
  text-align: center;
  font-size: 1.25rem;
}

.left h2 {
  text-align: left;
}

.left h3 {
  text-align: left;
}

p {
  text-align: justify !important
}

code{
  text-wrap: balance;
}

</style>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="diseño-factorial" class="level2 center">
<h2 class="center anchored" data-anchor-id="diseño-factorial">Diseño factorial</h2>
<section id="juan-carlos-gaviria-chaverra-andrés-orlando-lópez-henao" class="level3 center">
<h3 class="center anchored" data-anchor-id="juan-carlos-gaviria-chaverra-andrés-orlando-lópez-henao">Juan Carlos Gaviria Chaverra, Andrés Orlando López Henao</h3>
<p><strong>1. Plan y ejecución del experimento</strong></p>
<p><strong>1.1. Título del experimento</strong></p>
<p>Influencia de la arquitectura de redes neuronales convolucionales en la exactitud de predicción de señales de tránsito.</p>
<p><strong>1.2. Objetivos</strong></p>
<p>Evaluar cómo diferentes arquitecturas de redes neuronales convolucionales afectan la exactitud de predicción de señales de tránsito.</p>
<p><strong>1.3. Marco teórico</strong></p>
<p>Se ha observado un incremento significativo en la cantidad de fatalidades ocasionadas por percances automovilísticos a nivel global, siendo la causa primordial la falta de familiaridad con las indicaciones viales y las vías, aunque la razón más común es en parte el desconocimiento de ciertas señales viales específicas (OMS, 2022). Los incidentes de tránsito representan para la mayoría de las naciones un 3% de su producto interno bruto (PIB). Entre los años 2015 y 2030, se estima que estos incidentes tendrán un costo para la economía mundial de 1,8 billones de dólares, lo que equivale al 0,12% del PIB global (Al-Rousan et al., 2021). El aprendizaje automático consiste en un conjunto de técnicas y procedimientos destinados a generar inteligencia artificial mediante el uso de algoritmos y grandes volúmenes de datos con el fin de simular el proceso de aprendizaje (Gu et al., 2108). El aprendizaje profundo, como una subdivisión del aprendizaje automático, se basa en arquitecturas de redes neuronales con múltiples capas internas, tales como las Redes Neuronales Convolucionales (CNN) (Indolia et al., 2018). La identificación de señales de tráfico (TSR por sus siglas en inglés) constituye una tarea de visión artificial y aprendizaje automático que implica el reconocimiento y clasificación de señales de tráfico a partir de imágenes o secuencias de video (Liu et al., 2019). Los algoritmos de visión artificial para la detección de señales de tráfico se relacionan directamente con sus atributos distintivos. Principalmente, las señales de tráfico adoptan formas como triángulos, rectángulos, círculos u octágonos, además de presentar colores (Sheikah et al., 2016). Los colores empleados en las señales de tráfico suelen ser colores básicos como rojo, azul, negro, blanco, amarillo y, de forma menos frecuente, verde. Por ende, los enfoques de detección se clasifican principalmente en métodos basados en color y forma para determinar la característica de la imagen (Fan y Zhang, 2015). En el contexto de la visión por computadora, el reconocimiento de imágenes se refiere a la habilidad del software para identificar elementos, individuos, lugares, escritos y actividades en imágenes. Para llevar a cabo dicha identificación, los sistemas computacionales pueden emplear tecnologías de visión por computadora en combinación con cámaras y software basado en inteligencia artificial. (SearchEnterpriseAI).</p>
<p><strong>1.4. Variable respuesta</strong></p>
<p>Para el experimento, la variable respuesta es:</p>
<ul>
<li><p><strong><em>Variable</em></strong>: Exactitud de predicción.</p></li>
<li><p><strong><em>Valores usuales de operación</em></strong>: Entre 0 y 100.</p></li>
<li><p><strong><em>Precisión de medición</em></strong>: Porcentaje.</p></li>
<li><p><strong><em>Instrumento de medida</em></strong>: Computador.</p></li>
</ul>
<p><strong>1.5. Variables de control</strong></p>
<p>A continuación se describen las variables de control del experimento:</p>
<p>Tabla 1. Variables de control</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th><em>Variable</em></th>
<th><em>Valores usuales de operación</em></th>
<th><em>Precisión de medición</em></th>
<th><em>Instrumento de medida</em></th>
<th><em>Configuración propuesta</em></th>
<th><em>Efecto predicho</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Convoluciones</em></td>
<td>Entre 1 y 10</td>
<td>Número entero</td>
<td>No aplica</td>
<td>[1, 2]</td>
<td>La exactitud de predicción aumentará a mayor número de convoluciones.</td>
</tr>
<tr class="even">
<td><em>Filtros</em></td>
<td>Entre 1 y 100</td>
<td>Número entero</td>
<td>No aplica</td>
<td>[4, 16]</td>
<td>La exactitud de predicción aumentará a mayor número de filtros.</td>
</tr>
<tr class="odd">
<td><em>Densa</em></td>
<td>Entre 1 y 1000</td>
<td>Número entero</td>
<td>No aplica</td>
<td>[65, 128]</td>
<td>La exactitud de predicción aumentará a mayor número de neuronas en la capa densa.</td>
</tr>
</tbody>
</table>
<p><strong>1.6. Factores controlables</strong></p>
<p>En las tablas 2 y 3 se presentan los factores que se mantendrán constantes durante el experimento:</p>
<p>Tabla 2. Factores externos al modelo CNN</p>
<table class="table">
<colgroup>
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 27%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><em>Variable</em></th>
<th><em>Nivel deseado</em></th>
<th><em>Precisión de medición</em></th>
<th><em>Instrumento de medida</em></th>
<th><em>Control</em></th>
<th><em>Impacto esperado</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Dataset</em></td>
<td>Superior a 70000</td>
<td>Imágenes de 32x32 píxeles</td>
<td>No aplica</td>
<td>Se usarán las mismas 58511 imágenes de entrenamiento y 14630 imágenes de validación para todos los modelos</td>
<td>Obtención de una mejor comprensión de cómo diferentes configuraciones afectan el rendimiento del modelo, con el fin de identificar la arquitectura más adecuada para mejorar la exactitud predictiva.</td>
</tr>
</tbody>
</table>
<p>Tabla 3. Factores internos del modelo CNN</p>
<table class="table">
<colgroup>
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 24%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th><em>Variable</em></th>
<th><em>Nivel deseado</em></th>
<th><em>Precisión de medición</em></th>
<th><em>Instrumento de medida</em></th>
<th><em>Control</em></th>
<th><em>Impacto esperado</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Funcion de activación</em></td>
<td>Depende de la función seleccionada</td>
<td>No aplica</td>
<td>No aplica</td>
<td>Se aplicará la función de activación RELU para las capas convolucionales y la primera capa densa, y softwax para la última capa.</td>
<td>Obtenención de una consistencia en el comportamiento de los modelos y en una extracción de características más uniforme a lo largo de las capas.</td>
</tr>
<tr class="even">
<td><em>Compilación del modelo</em></td>
<td>No aplica</td>
<td>No aplica</td>
<td>No aplica</td>
<td><p>Se usarán los parametros:</p>
<p>loss=‘binary_crossentropy’</p>
<p>optimizer=‘adam’</p>
<p>metrics=[‘accuracy’]</p></td>
<td>Aseguramiento de la coherencia en el proceso de entrenamiento y evaluación. Esto garantiza que todos los modelos sean entrenados y evaluados de manera similar, facilitando la comparación de sus desempeños y simplificando la gestión de los experimentos de aprendizaje automático.</td>
</tr>
</tbody>
</table>
<p><strong>1.7. Factores no controlables</strong></p>
<p>A continuación se describen en las tablas 4 y 5 los factores que no se mantendrán constantes durante el experimento:</p>
<p>Tabla 4. Factores externos al modelo CNN</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 19%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th><em>Variable</em></th>
<th><em>Nivel deseado</em></th>
<th><em>Precisión de medición</em></th>
<th><em>Instrumento de medida</em></th>
<th>Estrategia</th>
<th><em>Efectos anticipados</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Procesamiento computacional</em></td>
<td>No aplica</td>
<td>No aplica</td>
<td>No aplica</td>
<td>Uso de configuraciones idénticas de hardware</td>
<td>Variación en el tiempo de procesamiento, limitando el número de muestras a tomar.</td>
</tr>
<tr class="even">
<td><em>Tiempo de entrenamiento por modelo</em></td>
<td>Entre 0 y 60</td>
<td>Minutos</td>
<td>Cronómetro</td>
<td>Uso de configuraciones idénticas de hardware</td>
<td>Limitación en el número de muestras a tomar.</td>
</tr>
</tbody>
</table>
<p>Tabla 5. Factores internos modelo CNN</p>
<table class="table">
<colgroup>
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th><em>Variable</em></th>
<th><em>Nivel deseado</em></th>
<th><em>Precisión de medición</em></th>
<th><em>Instrumento de medida</em></th>
<th><em>Estrategia</em></th>
<th>Efectos anticipados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Pesos</em></td>
<td>Entre 0 y 1</td>
<td>Número real</td>
<td>No aplica</td>
<td>Inicialización aleatoria</td>
<td>La inicialización aleatoria de pesos en una red neuronal convolucional promueve la diversidad desde el inicio del entrenamiento, ayudando a evitar mínimos locales y aumentando la capacidad del modelo para adaptarse a diferentes conjuntos de datos. Esto mejora la capacidad de generalización y la robustez del modelo.</td>
</tr>
</tbody>
</table>
<p><strong>1.8. Interacciones</strong></p>
<ol type="1">
<li><p>Interacción entre el número de convoluciones y el número de filtros.</p></li>
<li><p>Interacción entre el número de convoluciones y el número de neuronas de la capa densa.</p></li>
<li><p>Interacción entre el número de filtros y el número de neuronas de la capa densa.</p></li>
<li><p>Interacción entre el número de convoluciones, el número de filtros y el número de neuronas de la capa densa.</p></li>
</ol>
<p><strong>1.9. Restricciones</strong></p>
<p>Debido a los altos requisitos computacionales de los experimentos con redes neuronales convolucionales, fue necesario utilizar el servicio en la nube Google Colab. Tanto en sus versiones gratuitas como de pago, este servicio impone límites en el tiempo de ejecución. Cuando se agota este tiempo, es necesario esperar hasta el día siguiente para continuar. Por lo tanto, la principal limitación fue el tiempo de procesamiento proporcionado por el servicio, considerando un tiempo estimado de 10 minutos para el entrenamiento de cada modelo. Dado que se planeaba realizar pruebas con 8 modelos y realizar 10 ejecuciones de cada uno, se requerían al menos 14 horas de tiempo de computación.</p>
<p><strong>1.10. Diseño</strong></p>
<p>Se utilizará un diseño factorial el cual involucra tres factores: el numero de convoluciones, numero de filtros aplicados a cada convolucion y el numero de neuronas de la capa densa con lo cual se logrará medir el reconocimiento de señales de tráficos (TSDR) mediante el uso de una red neuronal convolucional (CNN) para determinar la significancia estadística de los efectos de los factores y sus interacciones para comprender como influyen en conjunto en la esactitud de la prediccion de la red neuronal al reconocer las imagenes de tránsito</p>
<p><strong>Factores:</strong></p>
<p>Para el experimento se tomaron los siguientes factores:</p>
<ul>
<li><p><strong><em>Convoluciones</em></strong>: Número de convoluciones</p></li>
<li><p><strong><em>Filtros</em></strong>: Número de filtros aplicados en cada convolución</p></li>
<li><p><strong><em>Densa</em></strong>: Número de neuronas de la capa densa final de la red neuronal</p></li>
</ul>
<p><strong>Tratamientos:</strong></p>
<p>La nomenclatura usada para identificar cada tratamiento es <strong>Cx_Fy_Dz</strong> donde: <em>x</em> representa el número de convoluciones, <em>y</em> representa número de filtros y <em>z</em> el numero de neuronas de la capa densa. De la combinación de los niveles de los factores, convoluciones, filtros y neuronas de la capa densa surgen los siguientes 8 tratamientos.</p>
<p>Tabla 6. Tratamientos</p>
<table class="table">
<thead>
<tr class="header">
<th>Identificador</th>
<th>Convoluciones</th>
<th>Filtros</th>
<th>Neuronas capa densa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C1_F4_D64</td>
<td>1</td>
<td>4</td>
<td>64</td>
</tr>
<tr class="even">
<td>C1_F4_D128</td>
<td>1</td>
<td>4</td>
<td>128</td>
</tr>
<tr class="odd">
<td>C1_F16_D64</td>
<td>1</td>
<td>16</td>
<td>64</td>
</tr>
<tr class="even">
<td>C1_F16_D128</td>
<td>1</td>
<td>16</td>
<td>128</td>
</tr>
<tr class="odd">
<td>C2_F4_D64</td>
<td>2</td>
<td>4</td>
<td>64</td>
</tr>
<tr class="even">
<td>C2_F4_D128</td>
<td>2</td>
<td>4</td>
<td>128</td>
</tr>
<tr class="odd">
<td>C2_F16_D64</td>
<td>2</td>
<td>16</td>
<td>64</td>
</tr>
<tr class="even">
<td>C2_F16_D128</td>
<td>2</td>
<td>16</td>
<td>128</td>
</tr>
</tbody>
</table>
<p><strong>Materiales:</strong></p>
<ul>
<li><p><strong>Entorno de ejecución:</strong> Google colab</p></li>
<li><p><strong>Lenguaje de programación:</strong> Python (TensorFlow y Keras)</p></li>
<li><p><strong>Conjunto de datos:</strong> <a href="https://www.kaggle.com/datasets/flo2607/traffic-signs-classification" class="uri">https://www.kaggle.com/datasets/flo2607/traffic-signs-classification</a></p></li>
<li><p><strong>Herramientas de análisis estadístico:</strong> Lenguaje de programación R</p></li>
<li><p><strong>Documentación y registro:</strong> Información de acceso libre</p></li>
</ul>
<p><strong>Procedimiento:</strong></p>
<ul>
<li><p>Definición de los factores</p></li>
<li><p>Determinar los niveles de los factores</p></li>
<li><p>Diseño del experimento factorial</p></li>
<li><p>Entrenamiento y evaluación de la CNN</p></li>
<li><p>Realización del análisis factorial:</p></li>
<li><p>Optimización y validación</p></li>
<li><p>Iteración y refinamiento</p></li>
</ul>
<p><strong>Análisis de Datos:</strong> Analizar la exactitud de los modelos para cada una de las configuraciones de la CNN que permitan establecer las interacciones que brinden los mejores porcentajes de predicción de las imágenes de tráfico dentro del diseño de análisis factorial de nivel</p>
<p><strong>Hipótesis:</strong></p>
<p><strong>Hipótesis de efecto principal</strong>: Las convulsiones, filtros y densas no tienen efectos principales significativos sobre la exactitud de la red neuronal convolucional (CNN).</p>
<p><strong>Hipótesis de interacciones:</strong> Las interacciones entre los diferentes factores no afectan conjuntamente el la exactitud de la red neuronal convolucional (CNN).</p>
<p><strong>Hipótesis de no linealidad:</strong> Los efectos de los factores son lineales<strong>.</strong></p>
<p><strong>Hipótesis de optimización:</strong> No existe una combinación optima de factoresque maximice la exactitud de la red neuronal convolucional.</p>
<p><strong>Resultados Esperados:</strong></p>
<p><strong>Efectos principales:</strong> Se espera que ciertos factores tengan impactos significativos en la exactitud de la red neuronal convolucional<strong>.</strong></p>
<p><strong>Interacciones entre factores:</strong> Se espera que se encuentren diferencias significativas entre los factores.</p>
<p><strong>Tendencias no lineales:</strong> Quelos efectos de ciertos factores no sean lineales.</p>
<p><strong>Configuraciones optimas:</strong> Quelas configuraciones optimas maximicen la exactitud de la red neuronal convolucional.</p>
<p><strong>1.11. Descripción</strong></p>
<p>La técnica de análisis y presentación utilizada en este experimento de 3 factores se basa en una combinación de herramientas estadísticas y gráficas diseñadas para explorar y comunicar los resultados de manera efectiva.</p>
<p><strong>Gráficas</strong> Se utilizan histogramas para visualizar la distribución de los datos en cada tratamiento, lo que permite una comprensión rápida de la forma y la dispersión de los datos. Los gráficos de cajas para comparar la distribución de los datos entre los diferentes tratamientos, mostrando la mediana, los cuartiles y los valores atípicos y los gráficos de dispersión para explorar la relación entre variables, como los valores ajustados y los residuos.</p>
<p><strong>ANOVAs:</strong> Se realiza un ANOVA para comparar las medias de los tratamientos y determinar si hay diferencias significativas entre ellos. Se evalúa la significancia estadística, lo que proporciona información sobre la variabilidad entre los tratamientos en relación con la variabilidad dentro de los tratamientos. Después de realizar el ANOVA, se realiza la prueba Tukey como una prueba para comparar todas las combinaciones posibles de pares de tratamientos y determinar qué diferencias son significativas.</p>
<p><strong>Modelos de Efectos, Medias y Regresión:</strong> Se utilizan diferentes modelos para analizar los datos según la pregunta de investigación. El modelo de efectos considera cada tratamiento como un factor independiente, mientras que el modelo de medias agrupa los tratamientos y compara las medias globales. El modelo de regresión permite explorar la relación entre la variable dependiente y las variables independientes.</p>
<p><strong>Pruebas de Homocedasticidad y Normalidad:</strong> Se realizan pruebas de homocedasticidad para evaluar si la varianza de los residuos es constante en todos los tratamientos.</p>
<p>Las pruebas de normalidad Anderson-Darling, Shapiro-Wilk, Jarque-Bera, Kolmogorov-Smirnov se utilizarán para verificar si los residuos siguen una distribución normal.</p>
<p><strong>Valores Ajustados vs Residuales e Independencia de Errores:</strong> Con las pruebas Levene, Bartlett, Breusch-Pagan y Durbin-Watson, Se examina la relación entre los valores ajustados y los residuos para evaluar la idoneidad del modelo. Además, se verifica la independencia de errores para garantizar que los errores no estén correlacionados entre sí</p>
<p><strong>Comparación entre Tratamientos:</strong> Se realizan comparaciones entre tratamientos utilizando los métodos de la diferencia significativa menos significativa (LSD) y la diferencia significativa honesta (HSD) para identificar las diferencias significativas entre los tratamientos y agruparlos en categorías homogéneas.</p>
<p>En resumen, esta técnica de análisis y presentación utiliza una variedad de herramientas estadísticas y gráficas para explorar y comunicar los resultados de manera efectiva en un experimento de 1 factor con 4 tratamientos. Se enfoca en la comparación de medias, la relación entre variables, la evaluación de la normalidad y homocedasticidad de los residuos, y la identificación de diferencias significativas entre tratamientos.</p>
<p><strong>1.12. Responsable de coordinación</strong></p>
<p>Andrés Orlando López Henao.</p>
<p><strong>1.13. Premuestreo</strong></p>
<p>Se llevó a cabo un premuestreo con el fin de establecer la configuración óptima del modelo CNN, buscando alcanzar una precisión superior al 70% sin sacrificar un tiempo de entrenamiento excesivo, dada la limitada capacidad de cómputo proporcionada por el servicio de Google Colab y las restricciones temporales del proyecto.</p>
<p>Inicialmente, se diseñaron dos modelos CNN:</p>
<ol type="1">
<li>Un modelo con 2 capas de convolución, cada una con 4 filtros, y una capa densa con 64 neuronas.</li>
<li>Un modelo con 4 capas de convolución, cada una con 16 filtros, y una capa densa con 128 neuronas.</li>
</ol>
<p>Ambos modelos fueron entrenados durante 3 épocas para evaluar su desempeño y tiempo de entrenamiento. Posteriormente, se incrementó gradualmente el número de épocas con la intención de alcanzar una precisión superior al 90%. Se encontró que el modelo de 2 convoluciones lograba esta precisión con 10 épocas, con un tiempo de entrenamiento medio entre 1 y 1.5 minutos por época. Sin embargo, el modelo de 4 convoluciones, a pesar de su mayor complejidad, no alcanzaba la precisión deseada en un tiempo aceptable, lo que podría atribuirse a la reducción excesiva de la imagen debido a la aplicación de múltiples convoluciones en imágenes tan pequeñas.</p>
<p>Ante la dificultad de entrenamiento y los límites de capacidad computacional, se evaluó un enfoque más simple con un modelo de 1 convolución, logrando la precisión esperada en menos de 1 minuto de entrenamiento por época, lo que demostró ser más eficiente y efectivo dadas las limitaciones del entorno de cómputo disponible.</p>
<p><strong>2. Análisis</strong></p>
<p><strong>2.1 Datos</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 6
   orden tratamiento convoluciones filtros densa exactitud
   &lt;dbl&gt; &lt;chr&gt;       &lt;fct&gt;         &lt;fct&gt;   &lt;fct&gt;     &lt;dbl&gt;
 1     1 C1_F4_D64   1             4       64         81.0
 2     2 C1_F4_D128  1             4       128        85.4
 3     3 C1_F16_D64  1             16      64         85.9
 4     4 C1_F16_D128 1             16      128        90.9
 5     5 C2_F4_D64   2             4       64         76.5
 6     6 C2_F4_D128  2             4       128        84.9
 7     7 C2_F16_D64  2             16      64         92.3
 8     8 C2_F16_D128 2             16      128        96.5
 9     9 C1_F4_D64   1             4       64         82.1
10    10 C1_F4_D128  1             4       128        86.7
# ℹ 40 more rows</code></pre>
</div>
</div>
<p><strong>2.2. Análisis exploratorio</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este análisis exploratorio de los tratamientos con respecto a la exactitud, podemos observar que posiblemente existan diferencias significativas entre algunos de los tratamientos con respecto al comportamiento del modelo de red neuronal, uno de los que mayor distancia toma con respecto a los otros es el arreglo C2_F16_D128, si se observa se puede ver, que los arreglos C1_F16_D64, C1_F4_D128, C1_F4_D64, están aparentemente distanciado del ya mencionado C2_F16_D128 quien por otro lado parece ser es el de mayor porcentaje de exactitud a la hora de predecir las imágenes de tránsito para corroborar dichas apreciaciones deberemos realizar un análisis de factores de efetos principales que permita establecer los valores de significancia entre los arreglos y la exactitud que brinda el modelo.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para el caso de estas interacciones entre convoluciones y la exactitud de manera exploratoria podemos ver que el numero de 2 convoluciones parece no distanciarse de una manera significativa de aquellos que solo presentan 1 convolución, por lo cual en este caso si es muy pertinente poder realizar un análisis mas detallado en las pruebas de significancia de las interacciones entre factores que nos puedan dar una mayor claridad de la relación entre estas dos características dentro del modelo de red neuronal.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Entre la exactitud y el factor filtro parece seguir el mismo comportamiento que el factor convolucional ya que no es claro poder observar diferencias directa entre este factor y la exactitud de igual modo debemos apelar al análisis de factores directos que permitan mostrar el valor de la significancia para con estas métricas poder concluir si realmente existen diferencias significativas directas entre este factor y la exactitud.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Entre la exactitud y capa densa parece nuevamente no haber diferencias ya que todas las cajas están en posiciones muy similares o almenos no se observa que alguna de ellas tome distancias considerables sobre las otras por lo que también es pertinente poder realizar pruebas de significancias que permitan comprobar dicho supuesto ya que de manera exploratoria no es claro que pueda haber diferencias. &nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mediante estos gráficos directos de caja entre exactitud y convoluciones es muchísimo mas claro ver que posiblemente no existan diferencias significativas entre la exactitud y la convolución ya que las cajas muestran tener unas formas y traslapes muy similares lo que posiblemente nos haría descartar dicha posibilidad que el p-value este por encima de 0,05.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mediante estos gráficos directos de caja, entre exactitud y filtros de manera exploratoria podemos ver la similitud en la distancia de las cajas con respeto a sus cuartiles, aunque la media pareciera inclinarse para el uso de 16 filtro no pareciera que esa distancia entre medias con respecto a los 4 filtros pueda llegar a presentar diferencia significativa sin embargo es importante poder comprobar este supuesto con la prueba de factores. &nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A través de la visualización de gráficos de caja comparativos entre la exactitud y la densidad de forma exploratoria, podemos observar similitudes en la distribución de los datos en términos de sus cuartiles. Aunque la media parece favorecer el uso de 128 neuronas en lugar de 64, no parece haber una diferencia significativa entre las medias de ambas configuraciones. No obstante, para validar esta suposición, nuevamente es crucial realizar pruebas de factores.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>$`1`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  78.84   86.47   91.05   90.28   94.22   98.37 

$`2`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  74.46   90.79   96.67   93.95   98.52   99.62 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$`4`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  74.46   85.27   90.29   89.73   95.00   99.02 

$`16`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  84.22   91.32   95.25   94.50   98.18   99.62 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$`64`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  74.46   85.73   91.64   90.15   94.42   99.14 

$`128`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  83.72   90.66   95.26   94.08   98.03   99.62 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Gráficos de medias</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 92.11468</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones</p>
<p>En estos 3 gráfico podemos observar de manera exploratoria como se distribuyen las medias con respecto a cada uno de los factores, pero además las diferencias que existen dentro de los valores de cada factor, en la primera grafica vemos que en el caso de las convoluciones se observa que la media con respecto a 2 capas es superior a la de 1 capa, pero en la gráfica; las pestañas se traslapan, lo que indica que a pesar de ser medias diferentes, posiblemente no existan diferencias entre los valores conjuntos, caso contrario se puede observar en las medias de los filtros y densas; logramos ver que en el primero, la media de 16 filtros es muy superior a la de 4, además vemos que en el gráfico las pestañas nos se traslapan, lo que en esta gráfica, podría darnos luces de la existencia de diferencias significativas en el uso de mayores filtros en la red neuronal, algo similar observamos en el factor densa, aunque son menores las diferencia entre las medias de 64 y 128 neuronas, también vemos que 128 podría funcionar mejor que 64 con respecto al modelo de exactitud de la red neuronal. Ya en el segundo gráfico observamos que entre los tres factores el que mas representan fuerza en la exactitud del modelo son el numero de filtros en segundo lugar el numero de neuronas y por ultimo las convoluciones, pero si miramos en detalle observamos que las diferencias entre los tres factores son muy mínimas situación que permite pensar que posiblemente no existan diferencias entre las interacciones. Ya en la 3 gráfica es evidente poder considerar que al no haber cruce entre las líneas para ninguno de los factores se podrían considerar la no existencia de diferencias significativa almenos dentro de ellos por lo cual es pertinente poder realizar la prueba entre factores para mirar si posiblemente existen diferencias entre las interacciones.</p>
<p><strong>2.3. ANOVA</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
convoluciones                1  269.8   269.8  10.767 0.001595 ** 
filtros                      1  456.7   456.7  18.228 5.89e-05 ***
densa                        1  309.6   309.6  12.357 0.000764 ***
convoluciones:filtros        1   31.5    31.5   1.256 0.266124    
convoluciones:densa          1    1.9     1.9   0.074 0.786039    
filtros:densa                1    6.2     6.2   0.248 0.619857    
convoluciones:filtros:densa  1   42.1    42.1   1.680 0.199089    
Residuals                   72 1804.1    25.1                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
filtros                1  456.7   456.7  18.060 6.24e-05 ***
densa                  1  309.6   309.6  12.243  0.00080 ***
convoluciones          1  269.8   269.8  10.667  0.00166 ** 
filtros:densa          1    6.2     6.2   0.246  0.62145    
densa:convoluciones    1    1.9     1.9   0.074  0.78699    
filtros:convoluciones  1   31.5    31.5   1.244  0.26827    
Residuals             73 1846.2    25.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21  5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuales
W = 0.97293, p-value = 0.08737</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  residuales
A = 0.69564, p-value = 0.06672</code></pre>
</div>
</div>
<p>Interpretaciones</p>
<p>Luego de realizar la prueba de normalidad de los datos con una prueba de Shapiro-Wilk: p-value de 0.08737 y otra de Anderson-Darling p-value de 0.06672, además de las pruebas de homocedasticidad Levane con valores de p-value de 0.1032221 además de la prueba de independencia de Durbin-Watson con p-value de xxxxxxx procedemos al confirmar todos los supuestos a realizar el análisis de varianza multifactorial lo cual En esta análisis de varianza multifactorial podemos ver la existencia de diferencias significativas de la variable de respuesta exactitud con respecto a cada uno de los factores, convoluciones, filtros y densa ya que observamos en el p-value de la prueba está por debajo de 0,05 lo que establece y corrobora la existencia de diferencias significativas en cada uno de los factores para cada uno de los factores con respecto a la variable de respuesta exactitud de predicción de la red en el caso de la lectura de las imágenes, caso contrario muestran las interacciones dobles; convoluciones:filtros, convoluciones:densa, filtros:densa, donde encontramos que estas interacciones sus p-value están por encima de 0,05, al igual que las interacciones entre los tres factores convoluciones.filtro:densa por lo cual podemos concluir la no existencia de diferencias significativas entre las interacciones, lo cual podríamos decir que estas no aportan a los porcentajes de exactitud del modelo de red neuronal convolucional (CNN).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = exactitud ~ as.numeric(convoluciones) * as.numeric(filtros) * 
    as.numeric(densa), data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.351  -3.772   1.317   3.330   9.475 

Coefficients:
                                                                Estimate
(Intercept)                                                       97.628
as.numeric(convoluciones)                                        -14.062
as.numeric(filtros)                                              -10.368
as.numeric(densa)                                                 -8.364
as.numeric(convoluciones):as.numeric(filtros)                     11.213
as.numeric(convoluciones):as.numeric(densa)                        9.314
as.numeric(filtros):as.numeric(densa)                              7.589
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)   -5.803
                                                                Std. Error
(Intercept)                                                         17.698
as.numeric(convoluciones)                                           11.193
as.numeric(filtros)                                                 11.193
as.numeric(densa)                                                   11.193
as.numeric(convoluciones):as.numeric(filtros)                        7.079
as.numeric(convoluciones):as.numeric(densa)                          7.079
as.numeric(filtros):as.numeric(densa)                                7.079
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)      4.477
                                                                t value
(Intercept)                                                       5.516
as.numeric(convoluciones)                                        -1.256
as.numeric(filtros)                                              -0.926
as.numeric(densa)                                                -0.747
as.numeric(convoluciones):as.numeric(filtros)                     1.584
as.numeric(convoluciones):as.numeric(densa)                       1.316
as.numeric(filtros):as.numeric(densa)                             1.072
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)  -1.296
                                                                Pr(&gt;|t|)    
(Intercept)                                                     5.14e-07 ***
as.numeric(convoluciones)                                          0.213    
as.numeric(filtros)                                                0.357    
as.numeric(densa)                                                  0.457    
as.numeric(convoluciones):as.numeric(filtros)                      0.118    
as.numeric(convoluciones):as.numeric(densa)                        0.192    
as.numeric(filtros):as.numeric(densa)                              0.287    
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)    0.199    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.006 on 72 degrees of freedom
Multiple R-squared:  0.3826,    Adjusted R-squared:  0.3225 
F-statistic: 6.373 on 7 and 72 DF,  p-value: 7.699e-06</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = exactitud ~ as.numeric(convoluciones) * as.numeric(filtros) * 
    as.numeric(densa), data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.351  -3.772   1.317   3.330   9.475 

Coefficients:
                                                                Estimate
(Intercept)                                                       97.628
as.numeric(convoluciones)                                        -14.062
as.numeric(filtros)                                              -10.368
as.numeric(densa)                                                 -8.364
as.numeric(convoluciones):as.numeric(filtros)                     11.213
as.numeric(convoluciones):as.numeric(densa)                        9.314
as.numeric(filtros):as.numeric(densa)                              7.589
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)   -5.803
                                                                Std. Error
(Intercept)                                                         17.698
as.numeric(convoluciones)                                           11.193
as.numeric(filtros)                                                 11.193
as.numeric(densa)                                                   11.193
as.numeric(convoluciones):as.numeric(filtros)                        7.079
as.numeric(convoluciones):as.numeric(densa)                          7.079
as.numeric(filtros):as.numeric(densa)                                7.079
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)      4.477
                                                                t value
(Intercept)                                                       5.516
as.numeric(convoluciones)                                        -1.256
as.numeric(filtros)                                              -0.926
as.numeric(densa)                                                -0.747
as.numeric(convoluciones):as.numeric(filtros)                     1.584
as.numeric(convoluciones):as.numeric(densa)                       1.316
as.numeric(filtros):as.numeric(densa)                             1.072
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)  -1.296
                                                                Pr(&gt;|t|)    
(Intercept)                                                     5.14e-07 ***
as.numeric(convoluciones)                                          0.213    
as.numeric(filtros)                                                0.357    
as.numeric(densa)                                                  0.457    
as.numeric(convoluciones):as.numeric(filtros)                      0.118    
as.numeric(convoluciones):as.numeric(densa)                        0.192    
as.numeric(filtros):as.numeric(densa)                              0.287    
as.numeric(convoluciones):as.numeric(filtros):as.numeric(densa)    0.199    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.006 on 72 degrees of freedom
Multiple R-squared:  0.3826,    Adjusted R-squared:  0.3225 
F-statistic: 6.373 on 7 and 72 DF,  p-value: 7.699e-06</code></pre>
</div>
</div>
<p>Interpretaciones …</p>
<p><strong>2.4. Diagrama de Pareto de efectos estandarizados</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<p><strong>Sin la interaccion triple</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
convoluciones          1  269.8   269.8  10.667  0.00166 ** 
filtros                1  456.7   456.7  18.060 6.24e-05 ***
densa                  1  309.6   309.6  12.243  0.00080 ***
convoluciones:filtros  1   31.5    31.5   1.244  0.26827    
convoluciones:densa    1    1.9     1.9   0.074  0.78699    
filtros:densa          1    6.2     6.2   0.246  0.62145    
Residuals             73 1846.2    25.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = exactitud ~ as.numeric(convoluciones) * as.numeric(filtros) + 
    as.numeric(convoluciones) * as.numeric(densa) + as.numeric(filtros) * 
    as.numeric(densa), data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.076  -3.219   0.844   3.740   8.749 

Coefficients:
                                              Estimate Std. Error t value
(Intercept)                                     78.043      9.256   8.432
as.numeric(convoluciones)                       -1.006      4.902  -0.205
as.numeric(filtros)                              2.688      4.902   0.548
as.numeric(densa)                                4.693      4.902   0.957
as.numeric(convoluciones):as.numeric(filtros)    2.509      2.249   1.116
as.numeric(convoluciones):as.numeric(densa)      0.610      2.249   0.271
as.numeric(filtros):as.numeric(densa)           -1.115      2.249  -0.496
                                              Pr(&gt;|t|)    
(Intercept)                                   2.17e-12 ***
as.numeric(convoluciones)                        0.838    
as.numeric(filtros)                              0.585    
as.numeric(densa)                                0.342    
as.numeric(convoluciones):as.numeric(filtros)    0.268    
as.numeric(convoluciones):as.numeric(densa)      0.787    
as.numeric(filtros):as.numeric(densa)            0.621    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.029 on 73 degrees of freedom
Multiple R-squared:  0.3682,    Adjusted R-squared:  0.3162 
F-statistic: 7.089 on 6 and 73 DF,  p-value: 5.656e-06</code></pre>
</div>
</div>
<p><strong>2.5. Identificacion de outlier</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>No Studentized residuals with Bonferroni p &lt; 0.05
Largest |rstudent|:
    rstudent unadjusted p-value Bonferroni p
21 -3.097868          0.0027789      0.22231</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Eliminacion de outlier</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
datos1$convoluciones                 1  269.8   269.8  10.667  0.00166 ** 
datos1$filtros                       1  456.7   456.7  18.060 6.24e-05 ***
datos1$densa                         1  309.6   309.6  12.243  0.00080 ***
datos1$convoluciones:datos1$filtros  1   31.5    31.5   1.244  0.26827    
datos1$convoluciones:datos1$densa    1    1.9     1.9   0.074  0.78699    
datos1$filtros:datos1$densa          1    6.2     6.2   0.246  0.62145    
Residuals                           73 1846.2    25.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
convoluciones          1  269.8   269.8  10.667  0.00166 ** 
filtros                1  456.7   456.7  18.060 6.24e-05 ***
densa                  1  309.6   309.6  12.243  0.00080 ***
convoluciones:filtros  1   31.5    31.5   1.244  0.26827    
convoluciones:densa    1    1.9     1.9   0.074  0.78699    
filtros:densa          1    6.2     6.2   0.246  0.62145    
Residuals             73 1846.2    25.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = datos1$exactitud ~ as.numeric(datos1$convoluciones) * 
    as.numeric(datos1$filtros) + as.numeric(datos1$convoluciones) * 
    as.numeric(datos1$densa) + as.numeric(datos1$filtros) * as.numeric(datos1$densa))

Residuals:
    Min      1Q  Median      3Q     Max 
-14.076  -3.219   0.844   3.740   8.749 

Coefficients:
                                                            Estimate Std. Error
(Intercept)                                                   78.043      9.256
as.numeric(datos1$convoluciones)                              -1.006      4.902
as.numeric(datos1$filtros)                                     2.688      4.902
as.numeric(datos1$densa)                                       4.693      4.902
as.numeric(datos1$convoluciones):as.numeric(datos1$filtros)    2.509      2.249
as.numeric(datos1$convoluciones):as.numeric(datos1$densa)      0.610      2.249
as.numeric(datos1$filtros):as.numeric(datos1$densa)           -1.115      2.249
                                                            t value Pr(&gt;|t|)
(Intercept)                                                   8.432 2.17e-12
as.numeric(datos1$convoluciones)                             -0.205    0.838
as.numeric(datos1$filtros)                                    0.548    0.585
as.numeric(datos1$densa)                                      0.957    0.342
as.numeric(datos1$convoluciones):as.numeric(datos1$filtros)   1.116    0.268
as.numeric(datos1$convoluciones):as.numeric(datos1$densa)     0.271    0.787
as.numeric(datos1$filtros):as.numeric(datos1$densa)          -0.496    0.621
                                                               
(Intercept)                                                 ***
as.numeric(datos1$convoluciones)                               
as.numeric(datos1$filtros)                                     
as.numeric(datos1$densa)                                       
as.numeric(datos1$convoluciones):as.numeric(datos1$filtros)    
as.numeric(datos1$convoluciones):as.numeric(datos1$densa)      
as.numeric(datos1$filtros):as.numeric(datos1$densa)            
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.029 on 73 degrees of freedom
Multiple R-squared:  0.3682,    Adjusted R-squared:  0.3162 
F-statistic: 7.089 on 6 and 73 DF,  p-value: 5.656e-06</code></pre>
</div>
</div>
<p><strong>2.6. Análisis de residuales</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-2.9301 -0.6700  0.1757  0.0000  0.7785  1.8213 </code></pre>
</div>
</div>
<p><strong>Prueba de normalidad</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21  5</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  los residuales siguen una distribución normal</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  los residuales no siguen una distribución normal</code></pre>
</div>
</div>
<p><strong>Prueba de normalidad Anderson-Darling</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  datos
A = 0.69564, p-value = 0.06672

Dado que el valor-p  0.06672455  es mayor que el nivel de significancia  0.05  no se rechaza H0, y se concluye que  los residuales siguen una distribución normal .</code></pre>
</div>
</div>
<p><strong>Prueba de normalidad Shapiro-Wilk</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  datos
W = 0.97293, p-value = 0.08737

Dado que el valor-p  0.08737433  es mayor que el nivel de significancia  0.05  no se rechaza H0, y se concluye que  los residuales siguen una distribución normal .</code></pre>
</div>
</div>
<p><strong>Prueba de varianza constante</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>interpretaciones…</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable convoluciones</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable convoluciones</code></pre>
</div>
</div>
<p><strong>Prueba de iguadad de varianzas Levene</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.1638 0.6868
      78               
Dado que el valor-p  0.686774  es mayor que el nivel de significancia  0.05  no se rechaza H0, y se concluye que  Las varianzas de la precisión son iguales en todos los niveles de la variable convoluciones .</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable filtros</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable filtros</code></pre>
</div>
</div>
<p><strong>Prueba de iguadad de varianzas Levene</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)  
group  1  6.6793 0.01162 *
      78                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Dado que el valor-p  0.01161968  es menor que el nivel de significancia  0.05  se rechaza H0, y se concluye que  Las varianzas de la precisión no son iguales en todos los niveles de la variable filtros .</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable densa</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable densa</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  2.7184 0.1032
      78               
Dado que el valor-p  0.1032221  es mayor que el nivel de significancia  0.05  no se rechaza H0, y se concluye que  Las varianzas de la precisión son iguales en todos los niveles de la variable densa .</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable convoluciones y filtros, y sus interacciones</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable convoluciones y filtros, y sus interacciones</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value    Pr(&gt;F)    
group  3  6.4349 0.0006094 ***
      76                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Dado que el valor-p  0.0006094097  es menor que el nivel de significancia  0.05  se rechaza H0, y se concluye que  Las varianzas de la precisión no son iguales en todos los niveles de la variable convoluciones y filtros, y sus interacciones .</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable convoluciones y densa, y sus interacciones</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable convoluciones y densa, y sus interacciones</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3    2.13 0.1034
      76               
Dado que el valor-p  0.1033795  es mayor que el nivel de significancia  0.05  no se rechaza H0, y se concluye que  Las varianzas de la precisión son iguales en todos los niveles de la variable convoluciones y densa, y sus interacciones .</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  Las varianzas de la precisión son iguales en todos los niveles de la variable densa y filtros, y sus interacciones</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  Las varianzas de la precisión no son iguales en todos los niveles de la variable densa y filtros, y sus interacciones</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value   Pr(&gt;F)   
group  3  5.5594 0.001673 **
      76                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Dado que el valor-p  0.001672774  es menor que el nivel de significancia  0.05  se rechaza H0, y se concluye que  Las varianzas de la precisión no son iguales en todos los niveles de la variable densa y filtros, y sus interacciones .</code></pre>
</div>
</div>
<p><strong>Prueba de independencia</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>En el gráfico de dispersión de los residuos en función de su orden dentro del conjunto de datos, no se observa un patrón claro en la distribución de los residuos a lo largo del orden. La mayoría de los residuos parecen estar dispersos aleatoriamente alrededor de la línea horizontal en y = 0, lo que sugiere que no hay un patrón sistemático en la relación entre el orden de los datos y los residuos.</li>
</ul>
<p><strong>Pruebas estadísticas</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>H0:  no hay autocorrelación en los residuos.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>HA:  hay autocorrelación en los residuos.</code></pre>
</div>
</div>
<p><strong>Prueba Durbin-Watson</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  datos
DW = 0.58876, p-value = 7.289e-13
alternative hypothesis: true autocorrelation is greater than 0

Dado que el valor-p  7.289006e-13  es menor que el nivel de significancia  0.05  se rechaza H0, y se concluye que  hay autocorrelación en los residuos. .[1] "."
Dado que el DW  0.5887562  no es cercano a 2 no se rechaza H0, y se concluye que  no hay autocorrelación en los residuos. .</code></pre>
</div>
</div>
<p><strong>2.7. Gráfico de superficie de respuesta</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Documento_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretaciones …</p>
<p><strong>Grafico con plotly</strong></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'plotly' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotly'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    last_plot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-d09c7fc7665135883016" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d09c7fc7665135883016">{"x":{"visdat":{"8ac773e1721":["function () ","plotlyVisDat"]},"cur_data":"8ac773e1721","attrs":{"8ac773e1721":{"x":[4,5,6,7,8,9,10,11,12,13,14,15,16],"y":[64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128],"z":[[6464.6627,6565.717,6666.7713,6767.8256,6868.8799,6969.9342,7070.9885,7172.0428,7273.0971,7374.1514,7475.2057,7576.26,7677.3143,7778.3686,7879.4229,7980.4772,8081.5315,8182.5858,8283.6401,8384.6944,8485.7487,8586.803,8687.8573,8788.9116,8889.9659,8991.0202,9092.0745,9193.1288,9294.1831,9395.2374,9496.2917,9597.346,9698.4003,9799.4546,9900.5089,10001.5632,10102.6175,10203.6718,10304.7261,10405.7804,10506.8347,10607.889,10708.9433,10809.9976,10911.0519,11012.1062,11113.1605,11214.2148,11315.2691,11416.3234,11517.3777,11618.432,11719.4863,11820.5406,11921.5949,12022.6492,12123.7035,12224.7578,12325.8121,12426.8664,12527.9207,12628.975,12730.0293,12831.0836,12932.1379],[7894.894,8018.5275,8142.161,8265.7945,8389.428,8513.0615,8636.695,8760.3285,8883.962,9007.5955,9131.229,9254.8625,9378.496,9502.1295,9625.763,9749.3965,9873.03,9996.6635,10120.297,10243.9305,10367.564,10491.1975,10614.831,10738.4645,10862.098,10985.7315,11109.365,11232.9985,11356.632,11480.2655,11603.899,11727.5325,11851.166,11974.7995,12098.433,12222.0665,12345.7,12469.3335,12592.967,12716.6005,12840.234,12963.8675,13087.501,13211.1345,13334.768,13458.4015,13582.035,13705.6685,13829.302,13952.9355,14076.569,14200.2025,14323.836,14447.4695,14571.103,14694.7365,14818.37,14942.0035,15065.637,15189.2705,15312.904,15436.5375,15560.171,15683.8045,15807.438],[9325.1253,9471.338,9617.5507,9763.7634,9909.9761,10056.1888,10202.4015,10348.6142,10494.8269,10641.0396,10787.2523,10933.465,11079.6777,11225.8904,11372.1031,11518.3158,11664.5285,11810.7412,11956.9539,12103.1666,12249.3793,12395.592,12541.8047,12688.0174,12834.2301,12980.4428,13126.6555,13272.8682,13419.0809,13565.2936,13711.5063,13857.719,14003.9317,14150.1444,14296.3571,14442.5698,14588.7825,14734.9952,14881.2079,15027.4206,15173.6333,15319.846,15466.0587,15612.2714,15758.4841,15904.6968,16050.9095,16197.1222,16343.3349,16489.5476,16635.7603,16781.973,16928.1857,17074.3984,17220.6111,17366.8238,17513.0365,17659.2492,17805.4619,17951.6746,18097.8873,18244.1,18390.3127,18536.5254,18682.7381],[10755.3566,10924.1485,11092.9404,11261.7323,11430.5242,11599.3161,11768.108,11936.8999,12105.6918,12274.4837,12443.2756,12612.0675,12780.8594,12949.6513,13118.4432,13287.2351,13456.027,13624.8189,13793.6108,13962.4027,14131.1946,14299.9865,14468.7784,14637.5703,14806.3622,14975.1541,15143.946,15312.7379,15481.5298,15650.3217,15819.1136,15987.9055,16156.6974,16325.4893,16494.2812,16663.0731,16831.865,17000.6569,17169.4488,17338.2407,17507.0326,17675.8245,17844.6164,18013.4083,18182.2002,18350.9921,18519.784,18688.5759,18857.3678,19026.1597,19194.9516,19363.7435,19532.5354,19701.3273,19870.1192,20038.9111,20207.703,20376.4949,20545.2868,20714.0787,20882.8706,21051.6625,21220.4544,21389.2463,21558.0382],[12185.5879,12376.959,12568.3301,12759.7012,12951.0723,13142.4434,13333.8145,13525.1856,13716.5567,13907.9278,14099.2989,14290.67,14482.0411,14673.4122,14864.7833,15056.1544,15247.5255,15438.8966,15630.2677,15821.6388,16013.0099,16204.381,16395.7521,16587.1232,16778.4943,16969.8654,17161.2365,17352.6076,17543.9787,17735.3498,17926.7209,18118.092,18309.4631,18500.8342,18692.2053,18883.5764,19074.9475,19266.3186,19457.6897,19649.0608,19840.4319,20031.803,20223.1741,20414.5452,20605.9163,20797.2874,20988.6585,21180.0296,21371.4007,21562.7718,21754.1429,21945.514,22136.8851,22328.2562,22519.6273,22710.9984,22902.3695,23093.7406,23285.1117,23476.4828,23667.8539,23859.225,24050.5961,24241.9672,24433.3383],[13615.8192,13829.7695,14043.7198,14257.6701,14471.6204,14685.5707,14899.521,15113.4713,15327.4216,15541.3719,15755.3222,15969.2725,16183.2228,16397.1731,16611.1234,16825.0737,17039.024,17252.9743,17466.9246,17680.8749,17894.8252,18108.7755,18322.7258,18536.6761,18750.6264,18964.5767,19178.527,19392.4773,19606.4276,19820.3779,20034.3282,20248.2785,20462.2288,20676.1791,20890.1294,21104.0797,21318.03,21531.9803,21745.9306,21959.8809,22173.8312,22387.7815,22601.7318,22815.6821,23029.6324,23243.5827,23457.533,23671.4833,23885.4336,24099.3839,24313.3342,24527.2845,24741.2348,24955.1851,25169.1354,25383.0857,25597.036,25810.9863,26024.9366,26238.8869,26452.8372,26666.7875,26880.7378,27094.6881,27308.6384],[15046.0505,15282.58,15519.1095,15755.639,15992.1685,16228.698,16465.2275,16701.757,16938.2865,17174.816,17411.3455,17647.875,17884.4045,18120.934,18357.4635,18593.993,18830.5225,19067.052,19303.5815,19540.111,19776.6405,20013.17,20249.6995,20486.229,20722.7585,20959.288,21195.8175,21432.347,21668.8765,21905.406,22141.9355,22378.465,22614.9945,22851.524,23088.0535,23324.583,23561.1125,23797.642,24034.1715,24270.701,24507.2305,24743.76,24980.2895,25216.819,25453.3485,25689.878,25926.4075,26162.937,26399.4665,26635.996,26872.5255,27109.055,27345.5845,27582.114,27818.6435,28055.173,28291.7025,28528.232,28764.7615,29001.291,29237.8205,29474.35,29710.8795,29947.409,30183.9385],[16476.2818,16735.3905,16994.4992,17253.6079,17512.7166,17771.8253,18030.934,18290.0427,18549.1514,18808.2601,19067.3688,19326.4775,19585.5862,19844.6949,20103.8036,20362.9123,20622.021,20881.1297,21140.2384,21399.3471,21658.4558,21917.5645,22176.6732,22435.7819,22694.8906,22953.9993,23213.108,23472.2167,23731.3254,23990.4341,24249.5428,24508.6515,24767.7602,25026.8689,25285.9776,25545.0863,25804.195,26063.3037,26322.4124,26581.5211,26840.6298,27099.7385,27358.8472,27617.9559,27877.0646,28136.1733,28395.282,28654.3907,28913.4994,29172.6081,29431.7168,29690.8255,29949.9342,30209.0429,30468.1516,30727.2603,30986.369,31245.4777,31504.5864,31763.6951,32022.8038,32281.9125,32541.0212,32800.1299,33059.2386],[17906.5131,18188.201,18469.8889,18751.5768,19033.2647,19314.9526,19596.6405,19878.3284,20160.0163,20441.7042,20723.3921,21005.08,21286.7679,21568.4558,21850.1437,22131.8316,22413.5195,22695.2074,22976.8953,23258.5832,23540.2711,23821.959,24103.6469,24385.3348,24667.0227,24948.7106,25230.3985,25512.0864,25793.7743,26075.4622,26357.1501,26638.838,26920.5259,27202.2138,27483.9017,27765.5896,28047.2775,28328.9654,28610.6533,28892.3412,29174.0291,29455.717,29737.4049,30019.0928,30300.7807,30582.4686,30864.1565,31145.8444,31427.5323,31709.2202,31990.9081,32272.596,32554.2839,32835.9718,33117.6597,33399.3476,33681.0355,33962.7234,34244.4113,34526.0992,34807.7871,35089.475,35371.1629,35652.8508,35934.5387],[19336.7444,19641.0115,19945.2786,20249.5457,20553.8128,20858.0799,21162.347,21466.6141,21770.8812,22075.1483,22379.4154,22683.6825,22987.9496,23292.2167,23596.4838,23900.7509,24205.018,24509.2851,24813.5522,25117.8193,25422.0864,25726.3535,26030.6206,26334.8877,26639.1548,26943.4219,27247.689,27551.9561,27856.2232,28160.4903,28464.7574,28769.0245,29073.2916,29377.5587,29681.8258,29986.0929,30290.36,30594.6271,30898.8942,31203.1613,31507.4284,31811.6955,32115.9626,32420.2297,32724.4968,33028.7639,33333.031,33637.2981,33941.5652,34245.8323,34550.0994,34854.3665,35158.6336,35462.9007,35767.1678,36071.4349,36375.702,36679.9691,36984.2362,37288.5033,37592.7704,37897.0375,38201.3046,38505.5717,38809.8388],[20766.9757,21093.822,21420.6683,21747.5146,22074.3609,22401.2072,22728.0535,23054.8998,23381.7461,23708.5924,24035.4387,24362.285,24689.1313,25015.9776,25342.8239,25669.6702,25996.5165,26323.3628,26650.2091,26977.0554,27303.9017,27630.748,27957.5943,28284.4406,28611.2869,28938.1332,29264.9795,29591.8258,29918.6721,30245.5184,30572.3647,30899.211,31226.0573,31552.9036,31879.7499,32206.5962,32533.4425,32860.2888,33187.1351,33513.9814,33840.8277,34167.674,34494.5203,34821.3666,35148.2129,35475.0592,35801.9055,36128.7518,36455.5981,36782.4444,37109.2907,37436.137,37762.9833,38089.8296,38416.6759,38743.5222,39070.3685,39397.2148,39724.0611,40050.9074,40377.7537,40704.6,41031.4463,41358.2926,41685.1389],[22197.207,22546.6325,22896.058,23245.4835,23594.909,23944.3345,24293.76,24643.1855,24992.611,25342.0365,25691.462,26040.8875,26390.313,26739.7385,27089.164,27438.5895,27788.015,28137.4405,28486.866,28836.2915,29185.717,29535.1425,29884.568,30233.9935,30583.419,30932.8445,31282.27,31631.6955,31981.121,32330.5465,32679.972,33029.3975,33378.823,33728.2485,34077.674,34427.0995,34776.525,35125.9505,35475.376,35824.8015,36174.227,36523.6525,36873.078,37222.5035,37571.929,37921.3545,38270.78,38620.2055,38969.631,39319.0565,39668.482,40017.9075,40367.333,40716.7585,41066.184,41415.6095,41765.035,42114.4605,42463.886,42813.3115,43162.737,43512.1625,43861.588,44211.0135,44560.439],[23627.4383,23999.443,24371.4477,24743.4524,25115.4571,25487.4618,25859.4665,26231.4712,26603.4759,26975.4806,27347.4853,27719.49,28091.4947,28463.4994,28835.5041,29207.5088,29579.5135,29951.5182,30323.5229,30695.5276,31067.5323,31439.537,31811.5417,32183.5464,32555.5511,32927.5558,33299.5605,33671.5652,34043.5699,34415.5746,34787.5793,35159.584,35531.5887,35903.5934,36275.5981,36647.6028,37019.6075,37391.6122,37763.6169,38135.6216,38507.6263,38879.631,39251.6357,39623.6404,39995.6451,40367.6498,40739.6545,41111.6592,41483.6639,41855.6686,42227.6733,42599.678,42971.6827,43343.6874,43715.6921,44087.6968,44459.7015,44831.7062,45203.7109,45575.7156,45947.7203,46319.725,46691.7297,47063.7344,47435.7391]],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"surface","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":[]},"yaxis":{"title":[]},"zaxis":{"title":[]}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"colorbar":{"title":"","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"x":[4,5,6,7,8,9,10,11,12,13,14,15,16],"y":[64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128],"z":[[6464.6627,6565.717,6666.7713,6767.8256,6868.8799,6969.9342,7070.9885,7172.0428,7273.0971,7374.1514,7475.2057,7576.26,7677.3143,7778.3686,7879.4229,7980.4772,8081.5315,8182.5858,8283.6401,8384.6944,8485.7487,8586.803,8687.8573,8788.9116,8889.9659,8991.0202,9092.0745,9193.1288,9294.1831,9395.2374,9496.2917,9597.346,9698.4003,9799.4546,9900.5089,10001.5632,10102.6175,10203.6718,10304.7261,10405.7804,10506.8347,10607.889,10708.9433,10809.9976,10911.0519,11012.1062,11113.1605,11214.2148,11315.2691,11416.3234,11517.3777,11618.432,11719.4863,11820.5406,11921.5949,12022.6492,12123.7035,12224.7578,12325.8121,12426.8664,12527.9207,12628.975,12730.0293,12831.0836,12932.1379],[7894.894,8018.5275,8142.161,8265.7945,8389.428,8513.0615,8636.695,8760.3285,8883.962,9007.5955,9131.229,9254.8625,9378.496,9502.1295,9625.763,9749.3965,9873.03,9996.6635,10120.297,10243.9305,10367.564,10491.1975,10614.831,10738.4645,10862.098,10985.7315,11109.365,11232.9985,11356.632,11480.2655,11603.899,11727.5325,11851.166,11974.7995,12098.433,12222.0665,12345.7,12469.3335,12592.967,12716.6005,12840.234,12963.8675,13087.501,13211.1345,13334.768,13458.4015,13582.035,13705.6685,13829.302,13952.9355,14076.569,14200.2025,14323.836,14447.4695,14571.103,14694.7365,14818.37,14942.0035,15065.637,15189.2705,15312.904,15436.5375,15560.171,15683.8045,15807.438],[9325.1253,9471.338,9617.5507,9763.7634,9909.9761,10056.1888,10202.4015,10348.6142,10494.8269,10641.0396,10787.2523,10933.465,11079.6777,11225.8904,11372.1031,11518.3158,11664.5285,11810.7412,11956.9539,12103.1666,12249.3793,12395.592,12541.8047,12688.0174,12834.2301,12980.4428,13126.6555,13272.8682,13419.0809,13565.2936,13711.5063,13857.719,14003.9317,14150.1444,14296.3571,14442.5698,14588.7825,14734.9952,14881.2079,15027.4206,15173.6333,15319.846,15466.0587,15612.2714,15758.4841,15904.6968,16050.9095,16197.1222,16343.3349,16489.5476,16635.7603,16781.973,16928.1857,17074.3984,17220.6111,17366.8238,17513.0365,17659.2492,17805.4619,17951.6746,18097.8873,18244.1,18390.3127,18536.5254,18682.7381],[10755.3566,10924.1485,11092.9404,11261.7323,11430.5242,11599.3161,11768.108,11936.8999,12105.6918,12274.4837,12443.2756,12612.0675,12780.8594,12949.6513,13118.4432,13287.2351,13456.027,13624.8189,13793.6108,13962.4027,14131.1946,14299.9865,14468.7784,14637.5703,14806.3622,14975.1541,15143.946,15312.7379,15481.5298,15650.3217,15819.1136,15987.9055,16156.6974,16325.4893,16494.2812,16663.0731,16831.865,17000.6569,17169.4488,17338.2407,17507.0326,17675.8245,17844.6164,18013.4083,18182.2002,18350.9921,18519.784,18688.5759,18857.3678,19026.1597,19194.9516,19363.7435,19532.5354,19701.3273,19870.1192,20038.9111,20207.703,20376.4949,20545.2868,20714.0787,20882.8706,21051.6625,21220.4544,21389.2463,21558.0382],[12185.5879,12376.959,12568.3301,12759.7012,12951.0723,13142.4434,13333.8145,13525.1856,13716.5567,13907.9278,14099.2989,14290.67,14482.0411,14673.4122,14864.7833,15056.1544,15247.5255,15438.8966,15630.2677,15821.6388,16013.0099,16204.381,16395.7521,16587.1232,16778.4943,16969.8654,17161.2365,17352.6076,17543.9787,17735.3498,17926.7209,18118.092,18309.4631,18500.8342,18692.2053,18883.5764,19074.9475,19266.3186,19457.6897,19649.0608,19840.4319,20031.803,20223.1741,20414.5452,20605.9163,20797.2874,20988.6585,21180.0296,21371.4007,21562.7718,21754.1429,21945.514,22136.8851,22328.2562,22519.6273,22710.9984,22902.3695,23093.7406,23285.1117,23476.4828,23667.8539,23859.225,24050.5961,24241.9672,24433.3383],[13615.8192,13829.7695,14043.7198,14257.6701,14471.6204,14685.5707,14899.521,15113.4713,15327.4216,15541.3719,15755.3222,15969.2725,16183.2228,16397.1731,16611.1234,16825.0737,17039.024,17252.9743,17466.9246,17680.8749,17894.8252,18108.7755,18322.7258,18536.6761,18750.6264,18964.5767,19178.527,19392.4773,19606.4276,19820.3779,20034.3282,20248.2785,20462.2288,20676.1791,20890.1294,21104.0797,21318.03,21531.9803,21745.9306,21959.8809,22173.8312,22387.7815,22601.7318,22815.6821,23029.6324,23243.5827,23457.533,23671.4833,23885.4336,24099.3839,24313.3342,24527.2845,24741.2348,24955.1851,25169.1354,25383.0857,25597.036,25810.9863,26024.9366,26238.8869,26452.8372,26666.7875,26880.7378,27094.6881,27308.6384],[15046.0505,15282.58,15519.1095,15755.639,15992.1685,16228.698,16465.2275,16701.757,16938.2865,17174.816,17411.3455,17647.875,17884.4045,18120.934,18357.4635,18593.993,18830.5225,19067.052,19303.5815,19540.111,19776.6405,20013.17,20249.6995,20486.229,20722.7585,20959.288,21195.8175,21432.347,21668.8765,21905.406,22141.9355,22378.465,22614.9945,22851.524,23088.0535,23324.583,23561.1125,23797.642,24034.1715,24270.701,24507.2305,24743.76,24980.2895,25216.819,25453.3485,25689.878,25926.4075,26162.937,26399.4665,26635.996,26872.5255,27109.055,27345.5845,27582.114,27818.6435,28055.173,28291.7025,28528.232,28764.7615,29001.291,29237.8205,29474.35,29710.8795,29947.409,30183.9385],[16476.2818,16735.3905,16994.4992,17253.6079,17512.7166,17771.8253,18030.934,18290.0427,18549.1514,18808.2601,19067.3688,19326.4775,19585.5862,19844.6949,20103.8036,20362.9123,20622.021,20881.1297,21140.2384,21399.3471,21658.4558,21917.5645,22176.6732,22435.7819,22694.8906,22953.9993,23213.108,23472.2167,23731.3254,23990.4341,24249.5428,24508.6515,24767.7602,25026.8689,25285.9776,25545.0863,25804.195,26063.3037,26322.4124,26581.5211,26840.6298,27099.7385,27358.8472,27617.9559,27877.0646,28136.1733,28395.282,28654.3907,28913.4994,29172.6081,29431.7168,29690.8255,29949.9342,30209.0429,30468.1516,30727.2603,30986.369,31245.4777,31504.5864,31763.6951,32022.8038,32281.9125,32541.0212,32800.1299,33059.2386],[17906.5131,18188.201,18469.8889,18751.5768,19033.2647,19314.9526,19596.6405,19878.3284,20160.0163,20441.7042,20723.3921,21005.08,21286.7679,21568.4558,21850.1437,22131.8316,22413.5195,22695.2074,22976.8953,23258.5832,23540.2711,23821.959,24103.6469,24385.3348,24667.0227,24948.7106,25230.3985,25512.0864,25793.7743,26075.4622,26357.1501,26638.838,26920.5259,27202.2138,27483.9017,27765.5896,28047.2775,28328.9654,28610.6533,28892.3412,29174.0291,29455.717,29737.4049,30019.0928,30300.7807,30582.4686,30864.1565,31145.8444,31427.5323,31709.2202,31990.9081,32272.596,32554.2839,32835.9718,33117.6597,33399.3476,33681.0355,33962.7234,34244.4113,34526.0992,34807.7871,35089.475,35371.1629,35652.8508,35934.5387],[19336.7444,19641.0115,19945.2786,20249.5457,20553.8128,20858.0799,21162.347,21466.6141,21770.8812,22075.1483,22379.4154,22683.6825,22987.9496,23292.2167,23596.4838,23900.7509,24205.018,24509.2851,24813.5522,25117.8193,25422.0864,25726.3535,26030.6206,26334.8877,26639.1548,26943.4219,27247.689,27551.9561,27856.2232,28160.4903,28464.7574,28769.0245,29073.2916,29377.5587,29681.8258,29986.0929,30290.36,30594.6271,30898.8942,31203.1613,31507.4284,31811.6955,32115.9626,32420.2297,32724.4968,33028.7639,33333.031,33637.2981,33941.5652,34245.8323,34550.0994,34854.3665,35158.6336,35462.9007,35767.1678,36071.4349,36375.702,36679.9691,36984.2362,37288.5033,37592.7704,37897.0375,38201.3046,38505.5717,38809.8388],[20766.9757,21093.822,21420.6683,21747.5146,22074.3609,22401.2072,22728.0535,23054.8998,23381.7461,23708.5924,24035.4387,24362.285,24689.1313,25015.9776,25342.8239,25669.6702,25996.5165,26323.3628,26650.2091,26977.0554,27303.9017,27630.748,27957.5943,28284.4406,28611.2869,28938.1332,29264.9795,29591.8258,29918.6721,30245.5184,30572.3647,30899.211,31226.0573,31552.9036,31879.7499,32206.5962,32533.4425,32860.2888,33187.1351,33513.9814,33840.8277,34167.674,34494.5203,34821.3666,35148.2129,35475.0592,35801.9055,36128.7518,36455.5981,36782.4444,37109.2907,37436.137,37762.9833,38089.8296,38416.6759,38743.5222,39070.3685,39397.2148,39724.0611,40050.9074,40377.7537,40704.6,41031.4463,41358.2926,41685.1389],[22197.207,22546.6325,22896.058,23245.4835,23594.909,23944.3345,24293.76,24643.1855,24992.611,25342.0365,25691.462,26040.8875,26390.313,26739.7385,27089.164,27438.5895,27788.015,28137.4405,28486.866,28836.2915,29185.717,29535.1425,29884.568,30233.9935,30583.419,30932.8445,31282.27,31631.6955,31981.121,32330.5465,32679.972,33029.3975,33378.823,33728.2485,34077.674,34427.0995,34776.525,35125.9505,35475.376,35824.8015,36174.227,36523.6525,36873.078,37222.5035,37571.929,37921.3545,38270.78,38620.2055,38969.631,39319.0565,39668.482,40017.9075,40367.333,40716.7585,41066.184,41415.6095,41765.035,42114.4605,42463.886,42813.3115,43162.737,43512.1625,43861.588,44211.0135,44560.439],[23627.4383,23999.443,24371.4477,24743.4524,25115.4571,25487.4618,25859.4665,26231.4712,26603.4759,26975.4806,27347.4853,27719.49,28091.4947,28463.4994,28835.5041,29207.5088,29579.5135,29951.5182,30323.5229,30695.5276,31067.5323,31439.537,31811.5417,32183.5464,32555.5511,32927.5558,33299.5605,33671.5652,34043.5699,34415.5746,34787.5793,35159.584,35531.5887,35903.5934,36275.5981,36647.6028,37019.6075,37391.6122,37763.6169,38135.6216,38507.6263,38879.631,39251.6357,39623.6404,39995.6451,40367.6498,40739.6545,41111.6592,41483.6639,41855.6686,42227.6733,42599.678,42971.6827,43343.6874,43715.6921,44087.6968,44459.7015,44831.7062,45203.7109,45575.7156,45947.7203,46319.725,46691.7297,47063.7344,47435.7391]],"type":"surface","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-2b3f3ca1176dc869d245" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-2b3f3ca1176dc869d245">{"x":{"visdat":{"8ac63c0109e":["function () ","plotlyVisDat"]},"cur_data":"8ac63c0109e","attrs":{"8ac63c0109e":{"x":[4,5,6,7,8,9,10,11,12,13,14,15,16],"y":[64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128],"z":[[6464.6627,6565.717,6666.7713,6767.8256,6868.8799,6969.9342,7070.9885,7172.0428,7273.0971,7374.1514,7475.2057,7576.26,7677.3143,7778.3686,7879.4229,7980.4772,8081.5315,8182.5858,8283.6401,8384.6944,8485.7487,8586.803,8687.8573,8788.9116,8889.9659,8991.0202,9092.0745,9193.1288,9294.1831,9395.2374,9496.2917,9597.346,9698.4003,9799.4546,9900.5089,10001.5632,10102.6175,10203.6718,10304.7261,10405.7804,10506.8347,10607.889,10708.9433,10809.9976,10911.0519,11012.1062,11113.1605,11214.2148,11315.2691,11416.3234,11517.3777,11618.432,11719.4863,11820.5406,11921.5949,12022.6492,12123.7035,12224.7578,12325.8121,12426.8664,12527.9207,12628.975,12730.0293,12831.0836,12932.1379],[7894.894,8018.5275,8142.161,8265.7945,8389.428,8513.0615,8636.695,8760.3285,8883.962,9007.5955,9131.229,9254.8625,9378.496,9502.1295,9625.763,9749.3965,9873.03,9996.6635,10120.297,10243.9305,10367.564,10491.1975,10614.831,10738.4645,10862.098,10985.7315,11109.365,11232.9985,11356.632,11480.2655,11603.899,11727.5325,11851.166,11974.7995,12098.433,12222.0665,12345.7,12469.3335,12592.967,12716.6005,12840.234,12963.8675,13087.501,13211.1345,13334.768,13458.4015,13582.035,13705.6685,13829.302,13952.9355,14076.569,14200.2025,14323.836,14447.4695,14571.103,14694.7365,14818.37,14942.0035,15065.637,15189.2705,15312.904,15436.5375,15560.171,15683.8045,15807.438],[9325.1253,9471.338,9617.5507,9763.7634,9909.9761,10056.1888,10202.4015,10348.6142,10494.8269,10641.0396,10787.2523,10933.465,11079.6777,11225.8904,11372.1031,11518.3158,11664.5285,11810.7412,11956.9539,12103.1666,12249.3793,12395.592,12541.8047,12688.0174,12834.2301,12980.4428,13126.6555,13272.8682,13419.0809,13565.2936,13711.5063,13857.719,14003.9317,14150.1444,14296.3571,14442.5698,14588.7825,14734.9952,14881.2079,15027.4206,15173.6333,15319.846,15466.0587,15612.2714,15758.4841,15904.6968,16050.9095,16197.1222,16343.3349,16489.5476,16635.7603,16781.973,16928.1857,17074.3984,17220.6111,17366.8238,17513.0365,17659.2492,17805.4619,17951.6746,18097.8873,18244.1,18390.3127,18536.5254,18682.7381],[10755.3566,10924.1485,11092.9404,11261.7323,11430.5242,11599.3161,11768.108,11936.8999,12105.6918,12274.4837,12443.2756,12612.0675,12780.8594,12949.6513,13118.4432,13287.2351,13456.027,13624.8189,13793.6108,13962.4027,14131.1946,14299.9865,14468.7784,14637.5703,14806.3622,14975.1541,15143.946,15312.7379,15481.5298,15650.3217,15819.1136,15987.9055,16156.6974,16325.4893,16494.2812,16663.0731,16831.865,17000.6569,17169.4488,17338.2407,17507.0326,17675.8245,17844.6164,18013.4083,18182.2002,18350.9921,18519.784,18688.5759,18857.3678,19026.1597,19194.9516,19363.7435,19532.5354,19701.3273,19870.1192,20038.9111,20207.703,20376.4949,20545.2868,20714.0787,20882.8706,21051.6625,21220.4544,21389.2463,21558.0382],[12185.5879,12376.959,12568.3301,12759.7012,12951.0723,13142.4434,13333.8145,13525.1856,13716.5567,13907.9278,14099.2989,14290.67,14482.0411,14673.4122,14864.7833,15056.1544,15247.5255,15438.8966,15630.2677,15821.6388,16013.0099,16204.381,16395.7521,16587.1232,16778.4943,16969.8654,17161.2365,17352.6076,17543.9787,17735.3498,17926.7209,18118.092,18309.4631,18500.8342,18692.2053,18883.5764,19074.9475,19266.3186,19457.6897,19649.0608,19840.4319,20031.803,20223.1741,20414.5452,20605.9163,20797.2874,20988.6585,21180.0296,21371.4007,21562.7718,21754.1429,21945.514,22136.8851,22328.2562,22519.6273,22710.9984,22902.3695,23093.7406,23285.1117,23476.4828,23667.8539,23859.225,24050.5961,24241.9672,24433.3383],[13615.8192,13829.7695,14043.7198,14257.6701,14471.6204,14685.5707,14899.521,15113.4713,15327.4216,15541.3719,15755.3222,15969.2725,16183.2228,16397.1731,16611.1234,16825.0737,17039.024,17252.9743,17466.9246,17680.8749,17894.8252,18108.7755,18322.7258,18536.6761,18750.6264,18964.5767,19178.527,19392.4773,19606.4276,19820.3779,20034.3282,20248.2785,20462.2288,20676.1791,20890.1294,21104.0797,21318.03,21531.9803,21745.9306,21959.8809,22173.8312,22387.7815,22601.7318,22815.6821,23029.6324,23243.5827,23457.533,23671.4833,23885.4336,24099.3839,24313.3342,24527.2845,24741.2348,24955.1851,25169.1354,25383.0857,25597.036,25810.9863,26024.9366,26238.8869,26452.8372,26666.7875,26880.7378,27094.6881,27308.6384],[15046.0505,15282.58,15519.1095,15755.639,15992.1685,16228.698,16465.2275,16701.757,16938.2865,17174.816,17411.3455,17647.875,17884.4045,18120.934,18357.4635,18593.993,18830.5225,19067.052,19303.5815,19540.111,19776.6405,20013.17,20249.6995,20486.229,20722.7585,20959.288,21195.8175,21432.347,21668.8765,21905.406,22141.9355,22378.465,22614.9945,22851.524,23088.0535,23324.583,23561.1125,23797.642,24034.1715,24270.701,24507.2305,24743.76,24980.2895,25216.819,25453.3485,25689.878,25926.4075,26162.937,26399.4665,26635.996,26872.5255,27109.055,27345.5845,27582.114,27818.6435,28055.173,28291.7025,28528.232,28764.7615,29001.291,29237.8205,29474.35,29710.8795,29947.409,30183.9385],[16476.2818,16735.3905,16994.4992,17253.6079,17512.7166,17771.8253,18030.934,18290.0427,18549.1514,18808.2601,19067.3688,19326.4775,19585.5862,19844.6949,20103.8036,20362.9123,20622.021,20881.1297,21140.2384,21399.3471,21658.4558,21917.5645,22176.6732,22435.7819,22694.8906,22953.9993,23213.108,23472.2167,23731.3254,23990.4341,24249.5428,24508.6515,24767.7602,25026.8689,25285.9776,25545.0863,25804.195,26063.3037,26322.4124,26581.5211,26840.6298,27099.7385,27358.8472,27617.9559,27877.0646,28136.1733,28395.282,28654.3907,28913.4994,29172.6081,29431.7168,29690.8255,29949.9342,30209.0429,30468.1516,30727.2603,30986.369,31245.4777,31504.5864,31763.6951,32022.8038,32281.9125,32541.0212,32800.1299,33059.2386],[17906.5131,18188.201,18469.8889,18751.5768,19033.2647,19314.9526,19596.6405,19878.3284,20160.0163,20441.7042,20723.3921,21005.08,21286.7679,21568.4558,21850.1437,22131.8316,22413.5195,22695.2074,22976.8953,23258.5832,23540.2711,23821.959,24103.6469,24385.3348,24667.0227,24948.7106,25230.3985,25512.0864,25793.7743,26075.4622,26357.1501,26638.838,26920.5259,27202.2138,27483.9017,27765.5896,28047.2775,28328.9654,28610.6533,28892.3412,29174.0291,29455.717,29737.4049,30019.0928,30300.7807,30582.4686,30864.1565,31145.8444,31427.5323,31709.2202,31990.9081,32272.596,32554.2839,32835.9718,33117.6597,33399.3476,33681.0355,33962.7234,34244.4113,34526.0992,34807.7871,35089.475,35371.1629,35652.8508,35934.5387],[19336.7444,19641.0115,19945.2786,20249.5457,20553.8128,20858.0799,21162.347,21466.6141,21770.8812,22075.1483,22379.4154,22683.6825,22987.9496,23292.2167,23596.4838,23900.7509,24205.018,24509.2851,24813.5522,25117.8193,25422.0864,25726.3535,26030.6206,26334.8877,26639.1548,26943.4219,27247.689,27551.9561,27856.2232,28160.4903,28464.7574,28769.0245,29073.2916,29377.5587,29681.8258,29986.0929,30290.36,30594.6271,30898.8942,31203.1613,31507.4284,31811.6955,32115.9626,32420.2297,32724.4968,33028.7639,33333.031,33637.2981,33941.5652,34245.8323,34550.0994,34854.3665,35158.6336,35462.9007,35767.1678,36071.4349,36375.702,36679.9691,36984.2362,37288.5033,37592.7704,37897.0375,38201.3046,38505.5717,38809.8388],[20766.9757,21093.822,21420.6683,21747.5146,22074.3609,22401.2072,22728.0535,23054.8998,23381.7461,23708.5924,24035.4387,24362.285,24689.1313,25015.9776,25342.8239,25669.6702,25996.5165,26323.3628,26650.2091,26977.0554,27303.9017,27630.748,27957.5943,28284.4406,28611.2869,28938.1332,29264.9795,29591.8258,29918.6721,30245.5184,30572.3647,30899.211,31226.0573,31552.9036,31879.7499,32206.5962,32533.4425,32860.2888,33187.1351,33513.9814,33840.8277,34167.674,34494.5203,34821.3666,35148.2129,35475.0592,35801.9055,36128.7518,36455.5981,36782.4444,37109.2907,37436.137,37762.9833,38089.8296,38416.6759,38743.5222,39070.3685,39397.2148,39724.0611,40050.9074,40377.7537,40704.6,41031.4463,41358.2926,41685.1389],[22197.207,22546.6325,22896.058,23245.4835,23594.909,23944.3345,24293.76,24643.1855,24992.611,25342.0365,25691.462,26040.8875,26390.313,26739.7385,27089.164,27438.5895,27788.015,28137.4405,28486.866,28836.2915,29185.717,29535.1425,29884.568,30233.9935,30583.419,30932.8445,31282.27,31631.6955,31981.121,32330.5465,32679.972,33029.3975,33378.823,33728.2485,34077.674,34427.0995,34776.525,35125.9505,35475.376,35824.8015,36174.227,36523.6525,36873.078,37222.5035,37571.929,37921.3545,38270.78,38620.2055,38969.631,39319.0565,39668.482,40017.9075,40367.333,40716.7585,41066.184,41415.6095,41765.035,42114.4605,42463.886,42813.3115,43162.737,43512.1625,43861.588,44211.0135,44560.439],[23627.4383,23999.443,24371.4477,24743.4524,25115.4571,25487.4618,25859.4665,26231.4712,26603.4759,26975.4806,27347.4853,27719.49,28091.4947,28463.4994,28835.5041,29207.5088,29579.5135,29951.5182,30323.5229,30695.5276,31067.5323,31439.537,31811.5417,32183.5464,32555.5511,32927.5558,33299.5605,33671.5652,34043.5699,34415.5746,34787.5793,35159.584,35531.5887,35903.5934,36275.5981,36647.6028,37019.6075,37391.6122,37763.6169,38135.6216,38507.6263,38879.631,39251.6357,39623.6404,39995.6451,40367.6498,40739.6545,41111.6592,41483.6639,41855.6686,42227.6733,42599.678,42971.6827,43343.6874,43715.6921,44087.6968,44459.7015,44831.7062,45203.7109,45575.7156,45947.7203,46319.725,46691.7297,47063.7344,47435.7391]],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"surface","contours":{"z":{"show":true,"usecolormap":true,"highlightcolor":"#ff0000","project":{"z":true}}},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"camera":{"eye":{"x":1.87,"y":0.88,"z":-0.64}},"xaxis":{"title":[]},"yaxis":{"title":[]},"zaxis":{"title":[]}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"colorbar":{"title":"","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"x":[4,5,6,7,8,9,10,11,12,13,14,15,16],"y":[64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128],"z":[[6464.6627,6565.717,6666.7713,6767.8256,6868.8799,6969.9342,7070.9885,7172.0428,7273.0971,7374.1514,7475.2057,7576.26,7677.3143,7778.3686,7879.4229,7980.4772,8081.5315,8182.5858,8283.6401,8384.6944,8485.7487,8586.803,8687.8573,8788.9116,8889.9659,8991.0202,9092.0745,9193.1288,9294.1831,9395.2374,9496.2917,9597.346,9698.4003,9799.4546,9900.5089,10001.5632,10102.6175,10203.6718,10304.7261,10405.7804,10506.8347,10607.889,10708.9433,10809.9976,10911.0519,11012.1062,11113.1605,11214.2148,11315.2691,11416.3234,11517.3777,11618.432,11719.4863,11820.5406,11921.5949,12022.6492,12123.7035,12224.7578,12325.8121,12426.8664,12527.9207,12628.975,12730.0293,12831.0836,12932.1379],[7894.894,8018.5275,8142.161,8265.7945,8389.428,8513.0615,8636.695,8760.3285,8883.962,9007.5955,9131.229,9254.8625,9378.496,9502.1295,9625.763,9749.3965,9873.03,9996.6635,10120.297,10243.9305,10367.564,10491.1975,10614.831,10738.4645,10862.098,10985.7315,11109.365,11232.9985,11356.632,11480.2655,11603.899,11727.5325,11851.166,11974.7995,12098.433,12222.0665,12345.7,12469.3335,12592.967,12716.6005,12840.234,12963.8675,13087.501,13211.1345,13334.768,13458.4015,13582.035,13705.6685,13829.302,13952.9355,14076.569,14200.2025,14323.836,14447.4695,14571.103,14694.7365,14818.37,14942.0035,15065.637,15189.2705,15312.904,15436.5375,15560.171,15683.8045,15807.438],[9325.1253,9471.338,9617.5507,9763.7634,9909.9761,10056.1888,10202.4015,10348.6142,10494.8269,10641.0396,10787.2523,10933.465,11079.6777,11225.8904,11372.1031,11518.3158,11664.5285,11810.7412,11956.9539,12103.1666,12249.3793,12395.592,12541.8047,12688.0174,12834.2301,12980.4428,13126.6555,13272.8682,13419.0809,13565.2936,13711.5063,13857.719,14003.9317,14150.1444,14296.3571,14442.5698,14588.7825,14734.9952,14881.2079,15027.4206,15173.6333,15319.846,15466.0587,15612.2714,15758.4841,15904.6968,16050.9095,16197.1222,16343.3349,16489.5476,16635.7603,16781.973,16928.1857,17074.3984,17220.6111,17366.8238,17513.0365,17659.2492,17805.4619,17951.6746,18097.8873,18244.1,18390.3127,18536.5254,18682.7381],[10755.3566,10924.1485,11092.9404,11261.7323,11430.5242,11599.3161,11768.108,11936.8999,12105.6918,12274.4837,12443.2756,12612.0675,12780.8594,12949.6513,13118.4432,13287.2351,13456.027,13624.8189,13793.6108,13962.4027,14131.1946,14299.9865,14468.7784,14637.5703,14806.3622,14975.1541,15143.946,15312.7379,15481.5298,15650.3217,15819.1136,15987.9055,16156.6974,16325.4893,16494.2812,16663.0731,16831.865,17000.6569,17169.4488,17338.2407,17507.0326,17675.8245,17844.6164,18013.4083,18182.2002,18350.9921,18519.784,18688.5759,18857.3678,19026.1597,19194.9516,19363.7435,19532.5354,19701.3273,19870.1192,20038.9111,20207.703,20376.4949,20545.2868,20714.0787,20882.8706,21051.6625,21220.4544,21389.2463,21558.0382],[12185.5879,12376.959,12568.3301,12759.7012,12951.0723,13142.4434,13333.8145,13525.1856,13716.5567,13907.9278,14099.2989,14290.67,14482.0411,14673.4122,14864.7833,15056.1544,15247.5255,15438.8966,15630.2677,15821.6388,16013.0099,16204.381,16395.7521,16587.1232,16778.4943,16969.8654,17161.2365,17352.6076,17543.9787,17735.3498,17926.7209,18118.092,18309.4631,18500.8342,18692.2053,18883.5764,19074.9475,19266.3186,19457.6897,19649.0608,19840.4319,20031.803,20223.1741,20414.5452,20605.9163,20797.2874,20988.6585,21180.0296,21371.4007,21562.7718,21754.1429,21945.514,22136.8851,22328.2562,22519.6273,22710.9984,22902.3695,23093.7406,23285.1117,23476.4828,23667.8539,23859.225,24050.5961,24241.9672,24433.3383],[13615.8192,13829.7695,14043.7198,14257.6701,14471.6204,14685.5707,14899.521,15113.4713,15327.4216,15541.3719,15755.3222,15969.2725,16183.2228,16397.1731,16611.1234,16825.0737,17039.024,17252.9743,17466.9246,17680.8749,17894.8252,18108.7755,18322.7258,18536.6761,18750.6264,18964.5767,19178.527,19392.4773,19606.4276,19820.3779,20034.3282,20248.2785,20462.2288,20676.1791,20890.1294,21104.0797,21318.03,21531.9803,21745.9306,21959.8809,22173.8312,22387.7815,22601.7318,22815.6821,23029.6324,23243.5827,23457.533,23671.4833,23885.4336,24099.3839,24313.3342,24527.2845,24741.2348,24955.1851,25169.1354,25383.0857,25597.036,25810.9863,26024.9366,26238.8869,26452.8372,26666.7875,26880.7378,27094.6881,27308.6384],[15046.0505,15282.58,15519.1095,15755.639,15992.1685,16228.698,16465.2275,16701.757,16938.2865,17174.816,17411.3455,17647.875,17884.4045,18120.934,18357.4635,18593.993,18830.5225,19067.052,19303.5815,19540.111,19776.6405,20013.17,20249.6995,20486.229,20722.7585,20959.288,21195.8175,21432.347,21668.8765,21905.406,22141.9355,22378.465,22614.9945,22851.524,23088.0535,23324.583,23561.1125,23797.642,24034.1715,24270.701,24507.2305,24743.76,24980.2895,25216.819,25453.3485,25689.878,25926.4075,26162.937,26399.4665,26635.996,26872.5255,27109.055,27345.5845,27582.114,27818.6435,28055.173,28291.7025,28528.232,28764.7615,29001.291,29237.8205,29474.35,29710.8795,29947.409,30183.9385],[16476.2818,16735.3905,16994.4992,17253.6079,17512.7166,17771.8253,18030.934,18290.0427,18549.1514,18808.2601,19067.3688,19326.4775,19585.5862,19844.6949,20103.8036,20362.9123,20622.021,20881.1297,21140.2384,21399.3471,21658.4558,21917.5645,22176.6732,22435.7819,22694.8906,22953.9993,23213.108,23472.2167,23731.3254,23990.4341,24249.5428,24508.6515,24767.7602,25026.8689,25285.9776,25545.0863,25804.195,26063.3037,26322.4124,26581.5211,26840.6298,27099.7385,27358.8472,27617.9559,27877.0646,28136.1733,28395.282,28654.3907,28913.4994,29172.6081,29431.7168,29690.8255,29949.9342,30209.0429,30468.1516,30727.2603,30986.369,31245.4777,31504.5864,31763.6951,32022.8038,32281.9125,32541.0212,32800.1299,33059.2386],[17906.5131,18188.201,18469.8889,18751.5768,19033.2647,19314.9526,19596.6405,19878.3284,20160.0163,20441.7042,20723.3921,21005.08,21286.7679,21568.4558,21850.1437,22131.8316,22413.5195,22695.2074,22976.8953,23258.5832,23540.2711,23821.959,24103.6469,24385.3348,24667.0227,24948.7106,25230.3985,25512.0864,25793.7743,26075.4622,26357.1501,26638.838,26920.5259,27202.2138,27483.9017,27765.5896,28047.2775,28328.9654,28610.6533,28892.3412,29174.0291,29455.717,29737.4049,30019.0928,30300.7807,30582.4686,30864.1565,31145.8444,31427.5323,31709.2202,31990.9081,32272.596,32554.2839,32835.9718,33117.6597,33399.3476,33681.0355,33962.7234,34244.4113,34526.0992,34807.7871,35089.475,35371.1629,35652.8508,35934.5387],[19336.7444,19641.0115,19945.2786,20249.5457,20553.8128,20858.0799,21162.347,21466.6141,21770.8812,22075.1483,22379.4154,22683.6825,22987.9496,23292.2167,23596.4838,23900.7509,24205.018,24509.2851,24813.5522,25117.8193,25422.0864,25726.3535,26030.6206,26334.8877,26639.1548,26943.4219,27247.689,27551.9561,27856.2232,28160.4903,28464.7574,28769.0245,29073.2916,29377.5587,29681.8258,29986.0929,30290.36,30594.6271,30898.8942,31203.1613,31507.4284,31811.6955,32115.9626,32420.2297,32724.4968,33028.7639,33333.031,33637.2981,33941.5652,34245.8323,34550.0994,34854.3665,35158.6336,35462.9007,35767.1678,36071.4349,36375.702,36679.9691,36984.2362,37288.5033,37592.7704,37897.0375,38201.3046,38505.5717,38809.8388],[20766.9757,21093.822,21420.6683,21747.5146,22074.3609,22401.2072,22728.0535,23054.8998,23381.7461,23708.5924,24035.4387,24362.285,24689.1313,25015.9776,25342.8239,25669.6702,25996.5165,26323.3628,26650.2091,26977.0554,27303.9017,27630.748,27957.5943,28284.4406,28611.2869,28938.1332,29264.9795,29591.8258,29918.6721,30245.5184,30572.3647,30899.211,31226.0573,31552.9036,31879.7499,32206.5962,32533.4425,32860.2888,33187.1351,33513.9814,33840.8277,34167.674,34494.5203,34821.3666,35148.2129,35475.0592,35801.9055,36128.7518,36455.5981,36782.4444,37109.2907,37436.137,37762.9833,38089.8296,38416.6759,38743.5222,39070.3685,39397.2148,39724.0611,40050.9074,40377.7537,40704.6,41031.4463,41358.2926,41685.1389],[22197.207,22546.6325,22896.058,23245.4835,23594.909,23944.3345,24293.76,24643.1855,24992.611,25342.0365,25691.462,26040.8875,26390.313,26739.7385,27089.164,27438.5895,27788.015,28137.4405,28486.866,28836.2915,29185.717,29535.1425,29884.568,30233.9935,30583.419,30932.8445,31282.27,31631.6955,31981.121,32330.5465,32679.972,33029.3975,33378.823,33728.2485,34077.674,34427.0995,34776.525,35125.9505,35475.376,35824.8015,36174.227,36523.6525,36873.078,37222.5035,37571.929,37921.3545,38270.78,38620.2055,38969.631,39319.0565,39668.482,40017.9075,40367.333,40716.7585,41066.184,41415.6095,41765.035,42114.4605,42463.886,42813.3115,43162.737,43512.1625,43861.588,44211.0135,44560.439],[23627.4383,23999.443,24371.4477,24743.4524,25115.4571,25487.4618,25859.4665,26231.4712,26603.4759,26975.4806,27347.4853,27719.49,28091.4947,28463.4994,28835.5041,29207.5088,29579.5135,29951.5182,30323.5229,30695.5276,31067.5323,31439.537,31811.5417,32183.5464,32555.5511,32927.5558,33299.5605,33671.5652,34043.5699,34415.5746,34787.5793,35159.584,35531.5887,35903.5934,36275.5981,36647.6028,37019.6075,37391.6122,37763.6169,38135.6216,38507.6263,38879.631,39251.6357,39623.6404,39995.6451,40367.6498,40739.6545,41111.6592,41483.6639,41855.6686,42227.6733,42599.678,42971.6827,43343.6874,43715.6921,44087.6968,44459.7015,44831.7062,45203.7109,45575.7156,45947.7203,46319.725,46691.7297,47063.7344,47435.7391]],"type":"surface","contours":{"z":{"show":true,"usecolormap":true,"highlightcolor":"#ff0000","project":{"z":true}}},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Interpretaciones …</p>
<p><strong>2.8. Comparaciones múltiples</strong></p>
<p>Interpretaciones …</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: pwr2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pwr2' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05240248</code></pre>
</div>
</div>
<p>Interpretaciones …</p>
<p><strong>2.9. Cálculo de réplicas</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<p>Interpretaciones …</p>
</section>
</section>
<section id="referencias" class="level1">
<h1>Referencias</h1>
<p>Al-Rousan, Taleb M. y Abdullahi A. Umar. Evaluación de los niveles de comprensión de las señales de tráfico entre los conductores en el Emirato de Abu Dhabi, Emiratos Árabes Unidos. Infraestructuras 6, núm. 9 (2021): 122. https://doi.org/10.3390/infrastructures6090122.</p>
<p>Fan, Y., Zhang, W. Detección y clasificación de señales de tráfico para sistemas avanzados de asistencia al conductor. En la 12.ª Conferencia Internacional sobre Sistemas Difusos y Descubrimiento de Conocimiento (FSKD), 2015, págs. 1335-1339.</p>
<p>Gu J., Wang Z., Kuen J., Ma L., Shahroudy A., Shuai B., Liu T., Wang X., Wang L., Wang G., Cai J., Chen T. Avances recientes en redes neuronales convolucionales. Reconocimiento de patrones, 2018, N 77, págs. 354-377. https://doi.org/10.1016/J.PATCOG.2017.10.013.</p>
<p>Indolia S., Goswami AK, Mishra SP, Asopa P. Comprensión conceptual de la red neuronal convolucional: un enfoque de aprendizaje profundo. Procedia Informática, 2018, N 132, págs. 679 – 688. https://doi.org/10.1016/J.PROCS.2018.05.069</p>
<p>Liu, S. Li, F. Chang e Y. Wang, “Métodos de detección de señales de tráfico basados en visión artificial: revisión, análisis y perspectivas”, en IEEE Access, vol.&nbsp;7, págs. 86578-86596, 2019, https://doi.org/10.1109/ACCESS.2019.2924947.</p>
<p>Organización mundial de la salud (OMS) 2022. Lesiones por accidentes de tráfico, “Organización Mundial de la Salud (OMS)”, [en línea], https://www.who.int/newsroom/factsheets/detail/road-lesiones de trafico.</p>
<p>Sheikh, AA, Kole, A., Maity, T. Detección y clasificación de señales de tráfico mediante funciones de color y redes neuronales. En Conferencia Internacional sobre Instrumentación y Energía de Control Inteligente (ICICPI), 2016, págs. 307-311.</p>
<p>Reconocimiento de imágenes, SearchEnterpriseAI [en línea] Disponible: https://www.techtarget.com/searchenterpriseai/definition/imagerecognition [Consultado el 19 de abril de 2024].</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>